### PR TITLE
Fixes #813: Only add frames if class file version supports attribute

### LINKED ISSUE #813: Instrumenting javax.servlet.http.HttpServlet emits stack map frame.
I was looking into a corrupted class file and found that the corruption came from the instrumentation of the Data Dog agent. Since this is probably a problem in Byte Buddy, I am eager to find out about it, of course.

The class file in question is `javax.servlet.http.HttpServlet` in Java version two which contained a *StackMapFrame* attribute for the `service(HttpServletRequest, HttpServletResponse)` method. For Java 2, this attribute should not exist and also seems broken and I wonder how it ended up there.

Could you look into how you instrument the servlet class and maybe set a breakpoint in `MethodWriter.visitFrame` to see if it is triggered during the instrumetation of the service class. If so, could you give me a stack trace of this call to see where it is coming from?

Also: are you using any manual ASM in your agent?

PS: This corruption has no consequence for loading the corrupted class file. The JVM ignores the class file attribute for stack map frames for Java 2 classes, no error will be raised, but class file parsing tools (in this case, another Byte Buddy-based agent) struggle with processing the class file.

PPS: I can reproduce it using your agent, I will look into it.

### PR DESCRIPTION
**Pull request by raphw**
Avoid corrupting the class file for any subsequent Java agents.

### CODE REVIEW

File: dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java [hunk 1]
```diff
@@ -40,6 +41,9 @@ public Size apply(final MethodVisitor mv, final Implementation.Context context)
               final Label logEnd = new Label();
               final Label eatException = new Label();
               final Label handlerExit = new Label();
+              
+              // Frames are only meaningful for class files in version 6 or later.
+              final boolean frames = context.getClassFileVersion().isAtLeast(ClassFileVersion.Java_V6);
```
Comment (tylerbenson) [inline dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java]: The build compile is currently failing because this line should be `JAVA_V6`.

**Comment by raphw** [comment]
Fixed it, that's what you get for not using an IDE for once.
